In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/janiobachmann/bank-marketing-dataset/bank.csv


In [2]:
df=pd.read_csv("/kaggle/input/datasets/janiobachmann/bank-marketing-dataset/bank.csv") 
#Read data file
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,blue-collar,single,primary,no,1,yes,no,cellular,20,apr,257,1,-1,0,unknown,no
11158,39,services,married,secondary,no,733,no,no,unknown,16,jun,83,4,-1,0,unknown,no
11159,32,technician,single,secondary,no,29,no,no,cellular,19,aug,156,2,-1,0,unknown,no
11160,43,technician,married,secondary,no,0,no,yes,cellular,8,may,9,2,172,5,failure,no


In [3]:
df.describe().round()

,age,balance,day,duration,campaign,pdays,previous
count,11162.0,11162.0,11162.0,11162.0,11162.0,11162.0,11162.0
mean,41.0,1529.0,16.0,372.0,3.0,51.0,1.0
std,12.0,3225.0,8.0,347.0,3.0,109.0,2.0
min,18.0,-6847.0,1.0,2.0,1.0,-1.0,0.0
25%,32.0,122.0,8.0,138.0,1.0,-1.0,0.0
50%,39.0,550.0,15.0,255.0,2.0,-1.0,0.0
75%,49.0,1708.0,22.0,496.0,3.0,21.0,1.0
max,95.0,81204.0,31.0,3881.0,63.0,854.0,58.0


In [4]:
df.isna().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [5]:
df=df.drop(columns =['job'])
df

,age,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,single,primary,no,1,yes,no,cellular,20,apr,257,1,-1,0,unknown,no
11158,39,married,secondary,no,733,no,no,unknown,16,jun,83,4,-1,0,unknown,no
11159,32,single,secondary,no,29,no,no,cellular,19,aug,156,2,-1,0,unknown,no
11160,43,married,secondary,no,0,no,yes,cellular,8,may,9,2,172,5,failure,no


In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
#leColumns=['marital','education','default','housing','loan','contact','poutcome','deposit']
df['marital']=le.fit_transform(df['marital'])
df['education']=le.fit_transform(df['education'])
df['default']=le.fit_transform(df['default'])
df['housing']=le.fit_transform(df['housing'])
df['loan']=le.fit_transform(df['loan'])
df['contact']=le.fit_transform(df['contact'])
df['poutcome']=le.fit_transform(df['poutcome'])
df['deposit']=le.fit_transform(df['deposit'])
df['month']=le.fit_transform(df['month'])
#df=df.drop(columns='month')
df

,age,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,1,1,0,2343,1,0,2,5,8,1042,1,-1,0,3,1
1,56,1,1,0,45,0,0,2,5,8,1467,1,-1,0,3,1
2,41,1,1,0,1270,1,0,2,5,8,1389,1,-1,0,3,1
3,55,1,1,0,2476,1,0,2,5,8,579,1,-1,0,3,1
4,54,1,2,0,184,0,0,2,5,8,673,2,-1,0,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,2,0,0,1,1,0,0,20,0,257,1,-1,0,3,0
11158,39,1,1,0,733,0,0,2,16,6,83,4,-1,0,3,0
11159,32,2,1,0,29,0,0,0,19,1,156,2,-1,0,3,0
11160,43,1,1,0,0,0,1,0,8,8,9,2,172,5,0,0


In [7]:
X=df.drop(columns='deposit')
y=df['deposit']
from sklearn.feature_selection import GenericUnivariateSelect
from sklearn.feature_selection import f_classif
FeatureSelect=GenericUnivariateSelect(score_func=f_classif ,param=65)
X_fclassif=FeatureSelect.fit_transform(X,y)
#X_fclassif.shape
#feature selection using GenericUnivariateSelect (f_classif0) 
FeatureSelect.get_support()

array([False, False,  True, False,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True])

In [8]:
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(random_state=42)
Feature_select=SelectFromModel(model ,threshold=-np.inf,max_features=10)
#threshold=-np.inf to enable max features =10
X_SFM=Feature_select.fit_transform(X,y)
X_SFM.shape
#feature selection using SelectFromModel (RandomForestClassifier) 
Feature_select.get_support()

array([ True, False, False, False,  True,  True, False,  True,  True,
        True,  True,  True,  True, False,  True])

In [9]:
from sklearn.model_selection import train_test_split
X_train ,X_test, y_train,y_test=train_test_split(
    X_fclassif,
    y,
    test_size=0.25,
    random_state=44,
    shuffle=True  
) #data split (test,train) fclassif

In [10]:
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier()
model.fit(X_train,y_train)
fclassif_predict=model.predict(X_test)
#train on fclassif selection features

In [11]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, fclassif_predict)
print(accuracy*100)
#fclassif acuuracy predict =81%

81.47617341454676


In [12]:
from sklearn.metrics import classification_report
print(classification_report(y_test, fclassif_predict))

              precision    recall  f1-score   support

           0       0.83      0.81      0.82      1449
           1       0.80      0.82      0.81      1342

    accuracy                           0.81      2791
   macro avg       0.81      0.81      0.81      2791
weighted avg       0.81      0.81      0.81      2791



In [13]:
#Select from model 
#split
from sklearn.model_selection import train_test_split
X_train ,X_test, y_train,y_test=train_test_split(
    X_SFM,
    y,
    test_size=0.25,
    random_state=44,
    shuffle=True  
)
#train
model = GradientBoostingClassifier()
model.fit(X_train,y_train)
SFM_predict=model.predict(X_test)
#train on SFM featurs


In [14]:
accuracy = accuracy_score(y_test, SFM_predict)
print(accuracy*100)
#SFM features accuracy =83%

83.69759942672877


In [15]:
print(classification_report(y_test, SFM_predict))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84      1449
           1       0.82      0.85      0.83      1342

    accuracy                           0.84      2791
   macro avg       0.84      0.84      0.84      2791
weighted avg       0.84      0.84      0.84      2791



In [16]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, SFM_predict))

[[1201  248]
 [ 207 1135]]


In [17]:
#randomfort model
model=RandomForestClassifier()
model.fit(X_train,y_train)
RF_predict=model.predict(X_test)
accuracy = accuracy_score(y_test, RF_predict)
print(accuracy*100)

84.70082407739162


In [18]:
print(classification_report(y_test, RF_predict))

              precision    recall  f1-score   support

           0       0.87      0.83      0.85      1449
           1       0.83      0.86      0.84      1342

    accuracy                           0.85      2791
   macro avg       0.85      0.85      0.85      2791
weighted avg       0.85      0.85      0.85      2791



In [19]:
print(confusion_matrix(y_test, RF_predict))
# Random Frost achieved better performance in terms of accuracy and recall.
# It also reduced false negatives, meaning fewer missed potential customers.

[[1205  244]
 [ 183 1159]]


In [20]:
features = Feature_select.get_support()

selected_features = X.columns[features]

print(selected_features)
# Selected features using SelectFromModel represent the most important predictors
# as determined by the underlying Random Forest model.

Index(['age', 'balance', 'housing', 'contact', 'day', 'month', 'duration',
       'campaign', 'pdays', 'poutcome'],
      dtype='object')
